hw09
kotoproger/home_work_basic pull request #10
Opened 2024-10-03 20:11 UTC by kotoproger

2024-10-04 04:17 UTC, vladislavmass requested changes

2024-10-04 04:17 UTC, vladislavmass commented on hw09_serialize/book/book.proto
> +message book{
Нет работы со слайсом книг. Для работа со слайдом необходимо добавить новое сообщение с repeated

2024-10-04 04:17 UTC, vladislavmass commented on hw09_serialize/book/json_test.go
> +			res, err := tc.book.MarshalJSON()
Этого делать не нада. MarshalJSON и .UnmarshalJSON вызываются внутри вызова json.Marshal и json.Unmarshal

2024-10-04 05:05 UTC, kotoproger commented on hw09_serialize/book/json_test.go
> +			res, err := tc.book.MarshalJSON()
заменил на json.Marshal(tc.book) и функция book.MarshalJSON не вызывается ...

2024-10-05 08:24 UTC, vladislavmass approved these changes

2024-10-05 08:37 UTC, merged